"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { TONGUE_TWISTERS } from "@/data/tongue-twisters";
import { AudioManager } from "@/lib/audio";
import { BombScheduler } from "@/lib/bomb-game";
import { COMMAND_DISPLAY_MS, GAME_AUDIO_SOURCES, SOUND_PATHS } from "@/lib/game-config";
import { pickRandom } from "@/lib/random";
import { storage } from "@/lib/storage";
import type { BombSettings, CommandId, DifficultySetting, EventDensity, ExplosionMode, TongueTwister } from "@/types/bomb";
import type { Player } from "@/types/player";

type Phase="rules"|"settings"|"twister"|"ready"|"playing"|"exploded";
const COMMANDS: Record<CommandId,{icon:string;label:string;detail:string}>={reverse:{icon:"🔄",label:"リバース！",detail:"回す方向を逆にする"},skipOne:{icon:"⏭",label:"1人飛ばし！",detail:"次の1人を飛ばす"},skipTwo:{icon:"⏩",label:"2人飛ばし！",detail:"次の2人を飛ばす"},repeatTwo:{icon:"✌️",label:"お前は2回じゃ！",detail:"早口言葉を2回連続で成功したら次の人へ"},repeatThree:{icon:"👹",label:"お前は3回じゃ！",detail:"早口言葉を3回連続で成功したら次の人へ"}};
const DEFAULT_SETTINGS:BombSettings={selectedPlayerIds:[],difficulty:"random",explosionMode:"normal",enabledCommands:Object.keys(COMMANDS) as CommandId[],eventDensity:"normal",fakeSounds:true};

export default function BombPage(){
 const [phase,setPhase]=useState<Phase>("rules"),[players,setPlayers]=useState<Player[]>([]),[settings,setSettings]=useState(DEFAULT_SETTINGS),[twister,setTwister]=useState<TongueTwister>(),[exhausted,setExhausted]=useState(false),[starter,setStarter]=useState(""),[roulette,setRoulette]=useState(false),[activeCommand,setActiveCommand]=useState<CommandId>(),[fakeFlash,setFakeFlash]=useState(false);
 const scheduler=useRef<BombScheduler>(),audio=useRef<AudioManager>(),displayTimer=useRef<ReturnType<typeof setTimeout>>(),fakeTimer=useRef<ReturnType<typeof setTimeout>>(),rouletteTimer=useRef<ReturnType<typeof setInterval>>(),commandBusy=useRef(false);
 const cleanup=useCallback(()=>{scheduler.current?.stop();scheduler.current=undefined;if(displayTimer.current)clearTimeout(displayTimer.current);if(fakeTimer.current)clearTimeout(fakeTimer.current);if(rouletteTimer.current)clearInterval(rouletteTimer.current);audio.current?.stopAll();commandBusy.current=false},[]);
 useEffect(()=>{const found=storage.getPlayers();setPlayers(found);setSettings(s=>({...s,selectedPlayerIds:found.map(p=>p.id)}));audio.current=new AudioManager();return cleanup},[cleanup]);
 const drawTwister=()=>{const used=storage.getUsedTongueTwisters();const available=TONGUE_TWISTERS.filter(t=>(settings.difficulty==="random"||t.difficulty===settings.difficulty)&&!used.includes(t.id));const next=pickRandom(available);if(!next){setExhausted(true);setTwister(undefined);return}storage.addUsedTongueTwister(next.id);setTwister(next);setExhausted(false)};
 const goTwister=()=>{drawTwister();setPhase("twister")};
 const selectedPlayers=players.filter(p=>settings.selectedPlayerIds.includes(p.id));
 const rouletteStart=()=>{if(selectedPlayers.length<2)return;audio.current?.stopEffects();audio.current?.unlock([SOUND_PATHS.roulette.decision]);audio.current?.play(SOUND_PATHS.roulette.drumroll,{loop:true});setRoulette(true);setStarter("");let count=0;rouletteTimer.current=setInterval(()=>{const next=pickRandom(selectedPlayers)?.name??"";setStarter(next);if(++count>=12){if(rouletteTimer.current)clearInterval(rouletteTimer.current);rouletteTimer.current=undefined;audio.current?.stopEffects();audio.current?.play(SOUND_PATHS.roulette.decision);setRoulette(false)}},100)};
 const onCommand=(id:CommandId)=>{commandBusy.current=true;setActiveCommand(id);audio.current?.stopEffects();audio.current?.play(SOUND_PATHS.commands[id],{duckTicking:true});if(displayTimer.current)clearTimeout(displayTimer.current);displayTimer.current=setTimeout(()=>{setActiveCommand(undefined);commandBusy.current=false;audio.current?.restoreTicking()},COMMAND_DISPLAY_MS)};
 const onFake=()=>{if(commandBusy.current)return;setFakeFlash(true);audio.current?.play(pickRandom(SOUND_PATHS.fake)??SOUND_PATHS.fake[0]);if(fakeTimer.current)clearTimeout(fakeTimer.current);fakeTimer.current=setTimeout(()=>setFakeFlash(false),900)};
 const explode=()=>{audio.current?.stopAll();audio.current?.play(SOUND_PATHS.explosion);setActiveCommand(undefined);setFakeFlash(false);setPhase("exploded")};
 const startGame=()=>{if(!twister)return;cleanup();audio.current?.unlock(GAME_AUDIO_SOURCES);audio.current?.startTicking(SOUND_PATHS.ticking);setPhase("playing");const next=new BombScheduler(settings,{explode,command:onCommand,fake:onFake});scheduler.current=next;next.start()};
 const homeGuard=(event:React.MouseEvent<HTMLAnchorElement>)=>{if(phase==="playing"&&!confirm("ゲームを終了しますか？\n爆弾タイマーと音声を停止します。")){event.preventDefault();return}cleanup()};
 const again=()=>{cleanup();setStarter("");setActiveCommand(undefined);setPhase("settings")};
 const select=<T extends string>(value:T,current:T,set:(value:T)=>void,label:string,sub?:string)=><button type="button" className={`option ${current===value?"selected":""}`} onClick={()=>set(value)}><b>{label}</b>{sub&&<><br/><small>{sub}</small></>}</button>;
 return <main className="shell">
  {phase==="rules"&&<><p className="eyebrow">BOMB GAME</p><h1>💣 爆弾ゲーム</h1><ol className="rules"><li>柔らかいボールを1個用意する</li><li>持っている人は、お題の早口言葉を言う</li><li>噛んだら最初から言い直す</li><li>成功したら次の人へ渡す</li><li>爆弾音が鳴った瞬間の保持者が負け</li></ol><h2>特殊指令</h2><div className="command-list">{Object.values(COMMANDS).map(c=><div key={c.label}><b>{c.icon} {c.label}</b><br/><small>{c.detail}</small></div>)}</div><p className="notice">フェイク効果音は鳴っても何も起きません。</p><div className="stack section"><button className="button" onClick={()=>setPhase("settings")}>設定へ進む</button><Link className="button secondary" href="/">HOMEへ戻る</Link></div></>}
  {phase==="settings"&&<><p className="eyebrow">BOMB / SETUP</p><h1>ゲーム設定</h1><section className="section"><h2>今回の参加者</h2>{players.length?<div className="stack">{players.map(p=><label className="check" key={p.id}><input type="checkbox" checked={settings.selectedPlayerIds.includes(p.id)} onChange={()=>setSettings(s=>({...s,selectedPlayerIds:s.selectedPlayerIds.includes(p.id)?s.selectedPlayerIds.filter(id=>id!==p.id):[...s.selectedPlayerIds,p.id]}))}/>{p.name}</label>)}</div>:<><p className="notice">参加者が登録されていません。登録なしでも遊べます。最初に持つ人はその場で決めてください。</p><Link className="button secondary" href="/players">参加者を登録する</Link></>}</section><section className="section"><h2>早口言葉の難しさ</h2><div className="option-grid">{([['random','おまかせ'],['easy','EASY'],['normal','NORMAL'],['hard','HARD']] as [DifficultySetting,string][]).map(([v,l])=>select(v,settings.difficulty,x=>setSettings(s=>({...s,difficulty:x})),l))}</div></section><section className="section"><h2>爆発まで</h2><div className="option-grid">{([['short','SHORT','10〜40秒'],['normal','NORMAL','20〜70秒'],['long','LONG','50〜120秒'],['chaos','CHAOS','10〜120秒']] as [ExplosionMode,string,string][]).map(([v,l,s])=>select(v,settings.explosionMode,x=>setSettings(o=>({...o,explosionMode:x})),l,s))}</div></section><section className="section"><h2>特殊指令</h2><div className="stack">{(Object.entries(COMMANDS) as [CommandId,(typeof COMMANDS)[CommandId]][]).map(([id,c])=><label className="check" key={id}><input type="checkbox" checked={settings.enabledCommands.includes(id)} onChange={()=>setSettings(s=>({...s,enabledCommands:s.enabledCommands.includes(id)?s.enabledCommands.filter(x=>x!==id):[...s.enabledCommands,id]}))}/>{c.icon} {c.label}</label>)}</div></section><section className="section"><h2>イベント量</h2><div className="option-grid">{([['low','少なめ'],['normal','普通'],['high','多め'],['brutal','鬼畜']] as [EventDensity,string][]).map(([v,l])=>select(v,settings.eventDensity,x=>setSettings(s=>({...s,eventDensity:x})),l))}</div></section><section className="section"><h2>フェイク効果音</h2><button className={`option ${settings.fakeSounds?'selected':''}`} onClick={()=>setSettings(s=>({...s,fakeSounds:!s.fakeSounds}))}>{settings.fakeSounds?"ON":"OFF"}</button></section><div className="stack section"><button className="button" onClick={goTwister}>早口言葉を決める</button><button className="button secondary" onClick={()=>setPhase("rules")}>遊び方へ戻る</button></div></>}
  {phase==="twister"&&<><p className="eyebrow">TONGUE TWISTER</p><h1>今回の早口言葉</h1>{exhausted?<div className="card center"><h2>この条件のお題を全部使いました。</h2><p className="muted">設定を変更するか、HOMEの出題履歴からリセットしてください。</p></div>:twister&&<div className="card"><div className="twister">「{twister.text}」</div><div className="twister-reading">{twister.reading}</div><p className="center muted">難易度：{twister.difficulty.toUpperCase()}</p></div>}<div className="stack section">{!exhausted&&<button className="button secondary" onClick={drawTwister}>別のお題</button>}{twister&&<button className="button" onClick={()=>setPhase("ready")}>これでいく！</button>}<button className="button secondary" onClick={()=>setPhase("settings")}>設定へ戻る</button></div></>}
  {phase==="ready"&&<><p className="eyebrow">WHO STARTS?</p><h1 className="center">最初に爆弾を<br/>持つ人を決めよう</h1>{selectedPlayers.length>=2?<div className="card center"><div className="bomb">🎯</div>{starter?<><p>最初は……</p><h2 className="title">{starter}！</h2></>:<p className="muted">ルーレットを回してください</p>}<button className="button secondary" disabled={roulette} onClick={rouletteStart}>{roulette?"抽選中…":"ルーレットSTART"}</button></div>:<div className="card center"><div className="bomb">🤲</div>{selectedPlayers.length===1?<><p>最初は……</p><h2>{selectedPlayers[0].name}！</h2></>:<h2>最初に持つ人を<br/>その場で決めてください。</h2>}<p className="muted">ボールを持って準備してください。</p></div>}<div className="stack section"><button className="button danger" onClick={startGame}>ゲームSTART</button><button className="button secondary" onClick={()=>setPhase("twister")}>早口言葉へ戻る</button></div></>}
  {phase==="playing"&&<><p className="eyebrow">BOMB IS LIVE</p><div className="center bomb">💣</div>{activeCommand&&<div className="command-overlay" role="status"><span className="command-icon">{COMMANDS[activeCommand].icon}</span><b>{COMMANDS[activeCommand].label}</b><p>{activeCommand==="repeatTwo"?"早口言葉を2回連続で成功せよ！":activeCommand==="repeatThree"?"早口言葉を3回連続で成功せよ！":COMMANDS[activeCommand].detail}</p></div>}<div className="card"><div className="twister">{twister?.text}</div><div className="twister-reading">{twister?.reading}</div><p className="center muted">噛まずに言えたら次へ渡せ！</p></div>{fakeFlash&&<p className="notice center">びっくりした？ フェイク！</p>}<Link className="button secondary section" href="/" onClick={homeGuard}>ゲームを終了してHOMEへ</Link></>}
  {phase==="exploded"&&<div className="center"><p className="eyebrow">GAME OVER</p><div className="explosion">💥💥💥</div><h1 className="title">ドカーン！！</h1><h2>持ってた人の負け！</h2><div className="stack section"><button className="button" onClick={again}>もう一回</button><Link className="button secondary" href="/" onClick={homeGuard}>HOMEへ</Link></div></div>}
 </main>;
}
